language: java
sudo: true
dist: trusty
jdk: oraclejdk9
addons:
  apt:
    packages:
      - oracle-java9-installer
services:
  - mysql
before_install:
  - chmod +x mvnw
  - mysql -e 'CREATE DATABASE IF NOT EXISTS enos;' 
  - mysql -e 'CREATE USER enos@localhost;'
  - mysql -e 'GRANT ALL PRIVILEGES ON enos.* TO enos@localhost;'
  - mysql -u enos --default-character-set=utf8 enos < scripts/enos.sql
